-- MOTHERSHIP Builder System — Schema Reference
-- Applied programmatically via src/builders/database.js initBuilderTables()
-- This file is documentation only — do not execute directly.

-- Projects: top-level groupings for related goals
CREATE TABLE IF NOT EXISTS builder_projects (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description_md TEXT,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','paused','complete')),
  created_at TEXT DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_builder_projects_status ON builder_projects(status);

-- Goals: detailed spec cards generated by Claude for builders to execute
CREATE TABLE IF NOT EXISTS builder_goals (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  objective TEXT NOT NULL,
  context_md TEXT,
  acceptance_criteria_md TEXT,
  steps_json TEXT DEFAULT '[]',        -- array of {title, detail} objects
  dependencies_json TEXT DEFAULT '[]', -- array of goal title strings
  priority INTEGER NOT NULL DEFAULT 3, -- 1 (highest) to 5 (lowest)
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','assigned','in_progress','done','cancelled')),
  generated_at TEXT DEFAULT (datetime('now')),
  generated_by_model TEXT,
  project_id TEXT
);

CREATE INDEX IF NOT EXISTS idx_builder_goals_status ON builder_goals(status);
CREATE INDEX IF NOT EXISTS idx_builder_goals_project ON builder_goals(project_id);
CREATE INDEX IF NOT EXISTS idx_builder_goals_priority ON builder_goals(priority);

-- Assignments: which builders are working on which goals
CREATE TABLE IF NOT EXISTS builder_goal_assignments (
  id TEXT PRIMARY KEY,
  goal_id TEXT NOT NULL,
  builder_telegram_chat_id TEXT NOT NULL,
  builder_name TEXT NOT NULL,
  assigned_at TEXT DEFAULT (datetime('now')),
  started_at TEXT,
  completed_at TEXT,
  status TEXT NOT NULL DEFAULT 'assigned' CHECK (status IN ('assigned','in_progress','done','dropped'))
);

CREATE INDEX IF NOT EXISTS idx_bga_goal ON builder_goal_assignments(goal_id);
CREATE INDEX IF NOT EXISTS idx_bga_builder ON builder_goal_assignments(builder_telegram_chat_id);
CREATE INDEX IF NOT EXISTS idx_bga_status ON builder_goal_assignments(status);

-- Profiles: registered builders and their metadata
CREATE TABLE IF NOT EXISTS builder_profiles (
  telegram_chat_id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  skills_json TEXT DEFAULT '[]',           -- array of skill strings
  active_goal_ids_json TEXT DEFAULT '[]',  -- maintained as a convenience cache
  joined_at TEXT DEFAULT (datetime('now')),
  last_active_at TEXT DEFAULT (datetime('now'))
);
